apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: devops
    tier: project
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort}}
  type: {{ .Values.service.type}}