apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops
      tier: project
      track: stable
  template:
    metadata:
      labels:
        app: devops
        tier: project
        track: stable
    spec:
      containers:
      - name: supercool
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deploymentPort.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  selector:
    app: devops
    tier: project
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort}}
  type: {{ .Values.service.type}}